# Generated by Django 4.2.7 on 2025-11-13 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coleccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("icono", models.CharField(max_length=10)),
                ("descripcion", models.TextField()),
                ("color", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="Obra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("historia", models.TextField()),
                ("proceso", models.TextField()),
                ("disponible", models.BooleanField(default=True)),
                ("tags", models.CharField(max_length=200)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "coleccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="galeria.coleccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObraFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="obras/")),
                ("descripcion", models.CharField(max_length=200)),
                ("es_principal", models.BooleanField(default=False)),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="galeria.obra"
                    ),
                ),
            ],
        ),
    ]
